name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          days-before-issue-stale: 60
          days-before-issue-close: 7
          days-before-pr-close: -1
---
name: "tagged-release"
on:
  push:
    tags:
      - "*"
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Test
        run: go build -v && go test ./...
      - name: Build for linux
        run: go build -o terraformer-all-linux-amd64
      - name: Build for mac
        run: GOOS=darwin go build -o terraformer-all-darwin-amd64
      - name: Build for windows
        run: GOOS=windows go build -o terraformer-all-windows-amd64
      - name: Build for all providers
        run: go run build/muilti-build/main.go

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            terraformer-*